/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:98e7a5a9b3f0cd299182b52601334f09:ad3644ce7dc7898af6ca3c5f3e2044b2:5bfa47a12fbbcfa9a150634d0b36efff$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class 
	{
		public const string PlayerRun = "playerRun";
	}
}